/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JEditorPane;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author omari
 */
public class Vista extends javax.swing.JFrame{

    /**
     * Creates new form interfaz
     */
    String nom_user;
    Modelo m;
    Control c;
    
    public Vista() {
        initComponents();
        chatEntry.setContentType("text/html");
        //msjEntry.setContentType("text/html");
        nom_user = JOptionPane.showInputDialog("Ingresa un nombre de usuario");
        if(nom_user == null)
            System.exit(1);
        this.setTitle(nom_user);
        this.setVisible(true);
        //btn_snd.setEnabled(false);
        m = new Modelo();
        c = new Control(m,this);
        c.initControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_snd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        msjEntry = new javax.swing.JEditorPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatEntry = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        lab_msj = new javax.swing.JLabel();
        lab_users = new javax.swing.JLabel();
        btn_conectar = new javax.swing.JButton();
        btn_dsct = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lst_users = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(nom_user);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btn_snd.setText("Enviar");

        jScrollPane2.setViewportView(msjEntry);

        chatEntry.setContentType("text/html"); // NOI18N
        chatEntry.setEnabled(true
        );
        jScrollPane1.setViewportView(chatEntry);

        lab_msj.setText("Escribe un mensaje:");

        lab_users.setText("Usuarios en linea");

        btn_conectar.setText("Conectar");

        btn_dsct.setText("Desconectar");

        jScrollPane4.setViewportView(lst_users);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_msj, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_conectar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_dsct)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 36, Short.MAX_VALUE)
                                        .addComponent(lab_users, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_snd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_users)
                    .addComponent(btn_conectar)
                    .addComponent(btn_dsct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(12, 12, 12)
                .addComponent(lab_msj, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_snd))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        c.enviarMensaje("<fin>" + nom_user);
    }//GEN-LAST:event_formWindowClosed
    
      
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
        
        
    }
    
    
    public JButton getBtn_conectar() {
        return btn_conectar;
    }

    public void setBtn_conectar(JButton btn_conectar) {
        this.btn_conectar = btn_conectar;
    }

    public JButton getBtn_dsct() {
        return btn_dsct;
    }

    public void setBtn_dsct(JButton btn_dsct) {
        this.btn_dsct = btn_dsct;
    }

    public JButton getBtn_snd() {
        return btn_snd;
    }

    public void setBtn_snd(JButton btn_snd) {
        this.btn_snd = btn_snd;
    }

    public JEditorPane getChatEntry() {
        return chatEntry;
    }

    public void setChatEntry(JEditorPane chatEntry) {
        this.chatEntry = chatEntry;
    }

    public JList<String> getLst_users() {
        return lst_users;
    }

    public void setLst_users(JList<String> lst_users) {
        this.lst_users = lst_users;
    }

    public JEditorPane getMsjEntry() {
        return msjEntry;
    }

    public void setMsjEntry(JEditorPane msjEntry) {
        this.msjEntry = msjEntry;
    }

    public String getNom_user() {
        return nom_user;
    }
    
    public void updateChatEntry(String msg){
        chatEntry.setText(msg);
    }
    
    public void updateUsersList(DefaultListModel dlm){
        lst_users.removeAll();
        lst_users.setModel(dlm);
    }
    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_conectar;
    private javax.swing.JButton btn_dsct;
    private javax.swing.JButton btn_snd;
    public javax.swing.JEditorPane chatEntry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lab_msj;
    private javax.swing.JLabel lab_users;
    private javax.swing.JList<String> lst_users;
    private javax.swing.JEditorPane msjEntry;
    // End of variables declaration//GEN-END:variables

}
