/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Sala;

/**
 *
 * @author omari
 */
public class CrearSala extends javax.swing.JFrame {
    
    File fichero;
    
    /**
     * Creates new form CrearSala
     */
    public CrearSala() {
        initNimbus();
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnPublico = new javax.swing.JToggleButton();
        BtnPrivada = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNombre = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        checkAcc = new javax.swing.JCheckBox();
        checkCom = new javax.swing.JCheckBox();
        checkTerror = new javax.swing.JCheckBox();
        checkDram = new javax.swing.JCheckBox();
        checkFicc = new javax.swing.JCheckBox();
        checkAni = new javax.swing.JCheckBox();
        checkCart = new javax.swing.JCheckBox();
        checkPol = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCode = new javax.swing.JTextPane();
        btnSelecArch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtArchivo = new javax.swing.JTextPane();
        btnCancel = new javax.swing.JButton();
        btnTransmicion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnPublico.setText("Pública");

        BtnPrivada.setText("Privada");

        jScrollPane1.setViewportView(txtNombre);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Descripción:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nombre de la película:");

        jScrollPane2.setViewportView(txtDescripcion);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Genero:");

        checkAcc.setText("Acción");

        checkCom.setText("Comedia");

        checkTerror.setText("Terror");

        checkDram.setText("Drama");

        checkFicc.setText("Ficción");

        checkAni.setText("Anime");

        checkCart.setText("Cartoon");

        checkPol.setText("Política");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkDram)
                    .addComponent(checkTerror)
                    .addComponent(checkCom)
                    .addComponent(checkAcc))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkPol)
                    .addComponent(checkFicc)
                    .addComponent(checkCart)
                    .addComponent(checkAni))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(checkFicc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkAni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkCart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkPol))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(checkTerror)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkAcc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkCom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkDram))))
        );

        jScrollPane3.setViewportView(txtCode);

        btnSelecArch.setText("Seleccionar Archivo");
        btnSelecArch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecArchActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Código (Sólo si es privada)");

        jScrollPane4.setViewportView(txtArchivo);

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnTransmicion.setText("Comenzar Transmición");
        btnTransmicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransmicionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(BtnPublico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnPrivada))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSelecArch))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTransmicion)
                                .addGap(49, 49, 49)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPublico)
                    .addComponent(BtnPrivada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecArch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnTransmicion))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSelecArchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecArchActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter("MP4 & MKV", "mp4", "mkv");
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(filter);
        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            fichero = fileChooser.getSelectedFile();
            txtArchivo.setText(fichero.getName()); 
        }
    }//GEN-LAST:event_btnSelecArchActionPerformed

    private void btnTransmicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransmicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransmicionActionPerformed

    
    private void initNimbus(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisorTransChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnPrivada;
    private javax.swing.JToggleButton BtnPublico;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSelecArch;
    private javax.swing.JButton btnTransmicion;
    private javax.swing.JCheckBox checkAcc;
    private javax.swing.JCheckBox checkAni;
    private javax.swing.JCheckBox checkCart;
    private javax.swing.JCheckBox checkCom;
    private javax.swing.JCheckBox checkDram;
    private javax.swing.JCheckBox checkFicc;
    private javax.swing.JCheckBox checkPol;
    private javax.swing.JCheckBox checkTerror;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane txtArchivo;
    private javax.swing.JTextPane txtCode;
    private javax.swing.JTextPane txtDescripcion;
    private javax.swing.JTextPane txtNombre;
    // End of variables declaration//GEN-END:variables
    
    public ArrayList<String> listaGeneros(){
        ArrayList<String> list = new ArrayList<>();
        if(checkAcc.isSelected())
            list.add("Accion");
        if(checkAni.isSelected())
            list.add("Anime");
        if(checkCart.isSelected())
            list.add("Cartoon");
        if(checkCom.isSelected())
            list.add("Comedia");
        if(checkDram.isSelected())
            list.add("Drama");
        if(checkFicc.isSelected())
            list.add("Ficcion");
        if(checkPol.isSelected())
            list.add("Politica");
        if(checkTerror.isSelected())
            list.add("Terror");
        return list;
    }
    
    public boolean validarInfo(){
        if(BtnPrivada.isSelected() && BtnPublico.isSelected()){
            JOptionPane.showMessageDialog(null, "Sólo debe seleccionar un tipo de transmición", "Alerta", 0);
            return false;
        }
        if(!BtnPrivada.isSelected() && !BtnPublico.isSelected()){
            JOptionPane.showMessageDialog(null, "Debe indicar el tipo de transmición", "Alerta", 0);
            return false;
        }
        if(txtNombre.getText().isBlank() || txtNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe indicar el nombre de la transmición", "Alerta", 0);
            return false;
        }
        if(txtDescripcion.getText().isBlank() || txtDescripcion.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe indicar el nombre de la transmición", "Alerta", 0);
            return false;
        }
        if(BtnPrivada.isSelected()){
            if(txtCode.getText().isBlank() || txtCode.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Debe indicar el código", "Alerta", 0);
                return false;
            }
        }
         if(txtArchivo.getText().isBlank() || txtArchivo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un archivo", "Alerta", 0);
            return false;
        }
        if(listaGeneros().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe seleccionar al menos un género", "Alerta", 0);
            return false;
        }
        return true;
    }
    
    public Sala generarSala(){
        Sala sala = new Sala();
        if(BtnPublico.isSelected()){
            sala.setPublica(true);
            sala.setCode("pub");
        }
        else{
            sala.setPublica(false);
            sala.setCode(txtCode.getText());
        }
        sala.setNombre(txtNombre.getText());
        sala.setDescripcion(txtDescripcion.getText());
        sala.setGenero(listaGeneros());
        sala.setPath(fichero.getAbsolutePath());
        return sala;
    }

    public JButton getBtnTransmicion() {
        return btnTransmicion;
    }

    

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public File getFichero() {
        return fichero;
    }
    
    
}
